[book]
title = "Pico Pico - Embedded Programming with Rust"
authors = ["ImplFerris"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/ImplFerris/pico-pico"
cname = "pico.implrust.com"
preferred-dark-theme = "ayu"
default-theme = "light"
mathjax-support = true

# Don't show table of contents for entire page in the navigation bar
# Pretty confusing to look at the chapter 
sidebar-header-nav = false

additional-css = ["theme/css/custom.css", "theme/tabs.css"]
additional-js = ["theme/tabs.js"]


[output.html.fold]
enable = true
level = 1     # the depth to start folding

[output.html.playground]
editable = true

[output.html.redirect]
# some backlinks points to old url
"/led/pwm-rp2350.html" = "/core-concepts/pwm/pwm-in-rp2350.html"
"/servo/pwm.html" = "/servo/how-servo-works.html"
"/servo/servo.html" = "/servo/index.html"

[preprocessor.tabs]
