[book]
title = "Pico Pico - Embedded Programming with Rust"
authors = ["ImplFerris"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/ImplFerris/pico-pico"
cname = "pico.implrust.com"
preferred-dark-theme = "ayu"
default-theme = "light"
mathjax-support = true

additional-css = ["theme/css/custom.css"]

[output.html.fold]
enable = true
level = 1     # the depth to start folding

[output.html.playground]
editable = true
